server:
  port: 8888
activemq:
  broker-url: tcp://172.16.1.50:61616
  user: admin
  password: admin
  org:
    apache:
      activemq:
        SERIALIZABLE_PACKAGES: java.lang,javax.security,java.util,org.apache.activemq,org.fusesource.hawtbuf,com.thoughtworks.xstream.mapper,com.bank.transfer
camunda.bpm:
  admin-user:
    id: kermit
    password: root
    firstName: Kermit
  filter:
    create: All tasks
mock:
  found:
    client:
      url: http://localhost:8080/mock/founds/client/1