server:
  port: 8888
activemq:
  broker-url: tcp://localhost:61616
  user: admin
  password: admin
  org:
    apache:
      activemq:
        SERIALIZABLE_PACKAGES: java.lang,javax.security,java.util,org.apache.activemq,org.fusesource.hawtbuf,com.thoughtworks.xstream.mapper,com.bank.transfer
camunda.bpm:
  admin-user:
    id: kermit
    password: root
    firstName: Kermit
  filter:
    create: All tasks
mock:
  soap:
    check-possibility: http://localhost:8091/CheckPossibilityService/services/CheckPossibilityService