//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 04:18:15 PM CET 
//


package com.bank.transfer.api.ws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="checkPossibilityReturn" type="{http://ws.com}CheckPossibilityServiceResponse"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "checkPossibilityReturn"
})
@XmlRootElement(name = "checkPossibilityResponse")
public class CheckPossibilityResponse {

    @XmlElement(required = true)
    protected CheckPossibilityServiceResponse checkPossibilityReturn;

    /**
     * Gets the value of the checkPossibilityReturn property.
     * 
     * @return
     *     possible object is
     *     {@link CheckPossibilityServiceResponse }
     *     
     */
    public CheckPossibilityServiceResponse getCheckPossibilityReturn() {
        return checkPossibilityReturn;
    }

    /**
     * Sets the value of the checkPossibilityReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link CheckPossibilityServiceResponse }
     *     
     */
    public void setCheckPossibilityReturn(CheckPossibilityServiceResponse value) {
        this.checkPossibilityReturn = value;
    }

}
